name: build all

on:
  # all branches:
  [ push, pull_request ]
  # trunk only:
  #push:
  #  branches: [ "trunk" ]
  #pull_request:
  #  branches: [ "trunk" ]

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@master
      # allow 'git describe' to work, by fetching tags and history
      with:
        fetch-depth: 0
        fetch-tags: true

    - name: Stop committing version.h
      # reject commit if version.h was changed
      run: grep 1969-07-20 ui/anduril/version.h

    - name: Requirements
      run: |
        sudo apt-get -qqy update
        sudo apt-get -qqy install avr-libc binutils-avr gcc-avr unzip wget

    - name: Cache Atmel DFPs
      id: cache-dfp
      uses: actions/cache@v3
      env:
        cache-name: cache-dfp-files
      with:
        path: arch/dfp
        # new cache whenever the dfp-install script changes
        key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('bin/dfp-install.sh') }}

    - name: Install Atmel DFPs
      if: steps.cache-dfp.outputs.cache-hit != 'true'
      run: |
        ./make dfp

    - name: Compile All
      run: |
        ./make
        echo "ARTIFACT_NAME=${GITHUB_WORKFLOW}-$(git rev-parse --short ${GITHUB_SHA})-${GITHUB_RUN_NUMBER}" >> "${GITHUB_ENV}"

    - name: Store Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.ARTIFACT_NAME }}
        if-no-files-found: error
        path: |
          hex/*.hex
